server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fds}
    username: ${SPRING_DATASOURCE_USERNAME:fds}
    password: ${SPRING_DATASOURCE_PASSWORD:fds}

  # Both property paths, so whichever Boot binds will work
  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:${SPRING_REDIS_HOST:redis}}
      port: ${SPRING_DATA_REDIS_PORT:${SPRING_REDIS_PORT:6379}}
